namespace Samples.MusicCollection.Api;

/// <summary>
/// 
/// </summary>
internal static class AutoGeneratedNamespaces
{
    #region Constant Declarations

    /// <summary>
    /// 
    /// </summary>
    public const string Handler = "Samples.MusicCollection.Api.Handler";

    #endregion
}